spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_db
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    hibernate:
#      ddl-auto: create
      ddl-auto: validate
    open-in-view: off
    database-platform: org.hibernate.dialect.MySQLDialect
  profiles:
    group:
      test: test-server
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/my_db
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    hibernate:
      #      ddl-auto: create
      ddl-auto: validate
    open-in-view: off
    database-platform: org.hibernate.dialect.MySQLDialect
