version: '3'

services:
  mysql:
    image: mysql:8.0
    volumes:
      - ./src/test/resources/data:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: password
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
